export const GET_POCEMONS_FAIL = "GET_POCEMONS_FAIL";
export const GET_POCEMONS_SUCCESS = "GET_POCEMONS_SUCCESS";
export const GET_POCEMONS_REQUEST = "GET_POCEMONS_REQUEST";
export const GET_POCEMON_FAIL = "GET_POCEMON_FAIL";
export const GET_POCEMON_SUCCESS = "GET_POCEMON_SUCCESS";
export const GET_POCEMON_REQUEST = "GET_POCEMON_REQUEST";
export const GET_CARD_POCEMON_FAIL = "GET_CARD_POCEMON_FAIL";
export const GET_CARD_POCEMON_SUCCESS = "GET_CARD_POCEMON_SUCCESS";
export const GET_CARD_POCEMON_REQUEST = "GET_CARD_POCEMON_REQUEST";
export const CLEARSTATE = "CLEARSTATE";

export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const GET_ALL_FROM_CARD = "GET_ALL_FROM_CARD";

